Features/set-up branch
melkamu372/Portfolio-mobile-first pull request #1
Opened 2023-07-11 08:01 UTC by melkamu372

Features/set-up branch added features are 

- add git ignore file
- add linter for css&html
- add git ignore file
- add style for index page

2023-07-11 19:15 UTC, topeogunleye requested changes
Hi @melkamu372, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 

**Toolbar Section**:

👍 The container of the section is a header tag.

👍 The logo is on the left and has a link (a tag). This is for three reasons: convention, semantics, and user experience(UX).

👍 The hamburger button is on the right, and has a nav tag. The nav tag is for semantics reason, and the right position for convention and user experience for mobile devices.

👍 The section has the proper background image (if the design has one). If an image is not part of the content (aesthetic reasons) use CSS background-image.

👍 The content is aligned with flexbox. This gives us a lot of options to align all our elements, plus, it's responsive.

👍 The section has the margins (top, bottom, left, right) defined in the design. Follow the original vision, if it's pretty and works, it will be a wonderful website.

👍 The section uses the font and colors (background and font) defined for the template.

**Headline Section:**

👍 The section has the proper background image (decorations are always background images, not img tags).

👍 The main title (e.g., "I'm Marianne ...") is a h1 tag.

👍 The paragraph  is a p tag.

👍 The list of icons uses a ul tag to group them, and li per icon; each icon has a link (a tag).

👍 The button is a link or button tag, and follow the button styling: Active, Hover and Pressed (see design).

👍 The content is aligned with flexbox.

👍 The section has the margins (top, bottom, left, right) defined in the design.

👍 The section uses the font and colors (background and font) defined for the template.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 19:15 UTC, topeogunleye commented on index.html
>      <div class="intro">
Hi, @melkamu372!

I noticed that you used a div tag for the container of the Headline section. However, the project requirements state that the container of the section should be a section tag. This is important for semantic and accessibility reasons, as it helps to structure your HTML document and make it more readable for screen readers and search engines.

To fix this issue, you should replace the div tag with a section tag and make sure to close it properly. For example:

```.html
<div class="intro"> // Replace this with <section className="intro">
  <h1 class="primary-text">I’m Melkamu Glad to see you!</h1>

  <!--- other html code -->
  <p className="headline-subtitle">Some subtitle</p>
</div> // Replace this with </section>
  <!--- other html code -->

```

Please make this change and resubmit your project. Thank you! 😊

2023-07-11 19:15 UTC, topeogunleye commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
Hi, @melkamu372!

I noticed that you didn't use a header tag for your subtitle text. However, the project requirements say that the subtitle (if existing) should use a header tag hx `(examples: <h1>,<h2>,<h3>, etc...)`. This is important for semantic and accessibility reasons, as it helps to define the hierarchy and importance of your content and make it more readable for screen readers and search engines.

To fix this issue, you should wrap your subtitle text in a header tag that matches the level of your main title. For example, because your main title is an `<h1>` tag, you could use an `<h2>` tag for your subtitle. For example:

```
<h1 className="main-title">Some title</h1>
<h2 className="subtitle">LET'S CONNECT</h2> // Use a header tag for your subtitle

```
Please make this change and resubmit your project. Thank you! 😊

2023-07-11 19:29 UTC, melkamu372 commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
Hello @topeogunleye thank you for your helpful remarks I updated the changes can you review now

2023-07-11 19:31 UTC, topeogunleye commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
@melkamu372, Thank you. please remember to push your changes to GitHub. 

Edit: You'll have to also submit again

2023-07-11 19:36 UTC, melkamu372 commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
@topeogunleye I push it does I request re review?

2023-07-11 19:36 UTC, melkamu372 commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
on dash board

2023-07-11 19:39 UTC, topeogunleye commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
Yes, you have to request a rereview through the dashboard 👍

2023-07-11 19:41 UTC, topeogunleye commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
@melkamu372 your "```
<p>I’m a software developer! I can help you build a product , feature or website
          Look
          through some of my work and experience! If you like what you see and have a project you need
          coded, don’t hestiate to contact me.</p>
``` is okay as a paragraph
          
          The only subtitle is the LET'S CONNECT text

2023-07-11 19:50 UTC, melkamu372 commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
@topeogunleye ok thank you I changed it

2023-07-11 19:53 UTC, melkamu372 commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
can I request now again

2023-07-11 20:00 UTC, topeogunleye commented on index.html
> +        <a href="#" class="link-text">LET’S CONNECT</a>
Yes, @melkamu372. Please do

2023-07-12 07:09 UTC, wayungi approved these changes
Hi @melkamu372 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All requested changes have been made ✔️ 
- [ ] All linter checks are passing ✔️ 
- [ ] Project up and running ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 19:43 UTC, merged