Feature/about my self
melkamu372/Portfolio-mobile-first pull request #2
Opened 2023-07-13 15:56 UTC by melkamu372

### New features added to the branch  _**feature/aboutMySelf**_  are

- add work section to the home page
- add assets for work and about me section
- add about about me section to home page
- add style for work and my self section

2023-07-13 23:13 UTC, DuaneDave requested changes
Hi @melkamu372  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ The UI looks quite good
✔️ Your code implementation is great

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 23:13 UTC, DuaneDave commented on index.html
> +          </div>
Please ensure to wrap the whole cards with one parent `section` tag that is aligned with `grid` and each individual card is aligned using `flex`, this will make dealing with the responsiveness quite easy.

2023-07-13 23:13 UTC, DuaneDave commented on index.html
> +            <h1 class="primary-text-about" id="about">About<br>Myself</h1>
Consider fixing the break of this text, and review the spacing that you are using in order not to allow the text to break 

FIGMA

<img width="190" alt="image" src="https://github.com/melkamu372/Portfolio-mobile-first/assets/84930355/6f309202-e2bb-415b-af52-a70c20bd1702">

Your design
<img width="225" alt="image" src="https://github.com/melkamu372/Portfolio-mobile-first/assets/84930355/29d7757b-1488-43fd-b0cc-afaf05a3c24f">

2023-07-13 23:13 UTC, DuaneDave commented on index.html
> +                <p>JavaScript</p>
To have a codebase that is really semantic, I recommend using a `ul` for each of the language, framework and technology sections, and each and every item is wrapped in their own `ul`.

Like this:

```
<ul>
  <li>
     <h4>framework</h4>
     <ul>
         <li>react</li>
    </ul>
  </li>
</ul>
```

2023-07-14 06:22 UTC, melkamu372 commented on index.html
> +            <h1 class="primary-text-about" id="about">About<br>Myself</h1>
@DuaneDave thank you I were doing based on the screen shoot provided in git hub now I updated based on  the figma.
https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md
![image](https://github.com/melkamu372/Portfolio-mobile-first/assets/47281626/503ab2b9-16ac-4e1e-867c-1fc4af5cc3e2)

2023-07-14 10:35 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi  @melkamu372         👋

Your project is complete! ✔️✔  🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors


- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 11:05 UTC, merged